version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3005:3000"
    depends_on:
      - backend
    networks:
      - frontend-network
    environment:
      - REACT_APP_API_URL=http://localhost:3006

  backend:
    build:
      context: ./backend
    ports:
      - "3006:5000"
    depends_on:
      - mongodb
    networks:
      - backend-network
    environment:
      - DATABASE_URL=mongodb://secure_user:securepassword@mongodb:27017/myappdb?authSource=admin
      - PORT=5000

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=secure_user
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
      - MONGO_INITDB_DATABASE=myappdb
    networks:
      - backend-network
    command: mongod --auth --bind_ip_all
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8080:8081"  # Expose only Mongo Express, not MongoDB
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=secure_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=securepassword
      - ME_CONFIG_MONGODB_SERVER=mongodb  # Must match the MongoDB service name
    depends_on:
      - mongodb
    networks:
      - backend-network  # Same network as MongoDB to allow connection

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  mongo-data:
