version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3005:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:3006

  backend:
    build:
      context: ./backend
    ports:
      - "3006:5000"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - DATABASE_URL=mongodb://admin:password@mongodb:27017/myappdb?authSource=admin
      - PORT=5000

  mongodb:
    image: mongo
    ports:
      - "3007:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=myappdb
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: